apiVersion: v1
kind: Pod
metadata:
  name: gpu-inspector
  namespace: default
spec:
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: "ip-100-64-171-112.us-west-2.compute.internal"
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: inspector
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    command: ["sh", "-c", "nvidia-smi && cat /etc/os-release || echo FAIL"]
    resources:
      limits:
        nvidia.com/gpu: "1"
