apiVersion: v1
kind: Namespace
metadata:
  name: deepseek-aibrix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    model.aibrix.ai/name: deepseek-r1-distill-llama-8b
    model.aibrix.ai/port: "8000"
  name: deepseek-r1-distill-llama-8b
  namespace: deepseek-aibrix
spec:
  replicas: 1
  selector:
    matchLabels:
      model.aibrix.ai/name: deepseek-r1-distill-llama-8b
  template:
    metadata:
      labels:
        model.aibrix.ai/name: deepseek-r1-distill-llama-8b
    spec:
      containers:
        - command: ["/bin/sh","-c"]
          args: ["vllm serve $MODEL --served-model-name $SERVED_MODEL_NAME --host 0.0.0.0 --port 8000 --max-num-seqs 4 --max-model-len 8192 --gpu-memory-utilization 0.95"]
          env:
            - name: VLLM_LOGGING_LEVEL
              value: "INFO"
            - name: MODEL
              value: "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
            - name: SERVED_MODEL_NAME
              value: "deepseek-r1-distill-llama-8b"
            # SECURITY: Inject Token from Secret
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: HUGGING_FACE_HUB_TOKEN
                  optional: true # Allowed to be missing for public models
          image: vllm/vllm-openai:v0.7.3
          imagePullPolicy: IfNotPresent
          name: vllm-openai
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: 1
            requests:
              cpu: 1
              memory: "12G"
              nvidia.com/gpu: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 120
            periodSeconds: 30
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: deepseek-r1-distill-llama-8b
  name: deepseek-r1-distill-llama-8b
  namespace: deepseek-aibrix
spec:
  ports:
    - name: serve
      port: 8000
      targetPort: 8000
  selector:
    model.aibrix.ai/name: deepseek-r1-distill-llama-8b
  type: ClusterIP
